import { Product } from "../models";

export const INITIAL_PRODUCTS_SEED = [
  {
    slug: "post-hair-transplant-kit",
    name: "Post Hair Transplant Kit",
    category: "Kits & Combos",
    concern: "Post-Transplant Care",
    price: 3200,
    originalPrice: 3285,
    rating: 4.9,
    reviewsCount: 142,
    isSale: true,
    badge: "Best Seller",
    isKit: true,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    description: "Complete clinical post-transplant care regimen ensuring maximum graft survival and gentle scalp healing.",
    status: "published" as const,
    sortOrder: 1,
    seoTitle: "Post Hair Transplant Kit | URoots by Anwar Clinic",
    seoDescription: "Clinical post-transplant care kit for follicle recovery and gentle scalp healing.",
    sections: {
      hero: {
        galleryImages: [
          "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
          "https://images.unsplash.com/photo-1608248597359-52e3794b6389?auto=format&fit=crop&w=800&q=80",
          "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
          "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
        ],
        suitableFor: [
          "Patients recovering from FUT / FUE / QHT procedures",
          "Individuals experiencing active hair thinning & shedding",
          "Safe for daily use on sensitive or irritated scalps",
        ],
      },
      whatsInside: {
        title: "What's Inside Your Kit",
        subtitle: "WHAT'S INCLUDED",
        items: [
          {
            title: "URoots Shampoo with Aloe Vera and Pro-Moisturisers",
            description: "Gentle daily-use moisturising formula developed to cleanse the sensitive post-transplant scalp without stripping lipids.",
            image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80",
          },
          {
            title: "URoots Hair Serum (Redensyl + Procapil)",
            description: "Advanced daily care follicle activation serum formulated with Redensyl and Procapil.",
            image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
          },
          {
            title: "URoots Hair Supplement Multivitamin",
            description: "Daily nutraceutical multivitamin formulated with Biotin, Zinc, Pumpkin Seed, and vital amino acids.",
            image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
          },
          {
            title: "URoots Finasil Tablets IP 1mg for Men",
            description: "Formulated with pharmaceutical grade DHT blockers to stop progressive follicle miniaturization.",
            image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
          },
          {
            title: "Gemline-D3 Vitamin D3 Capsules",
            description: "High-potency vitamin D3 supplement to replenish cellular micro-nutrients needed for new follicular cycling.",
            image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
          },
        ],
      },
      keyBenefits: {
        title: "Key Benefits",
        subtitle: "EXPLORE OUR",
        description: "Complete scalp activation, follicle nourishment, and nutritional support in a single structured routine designed to support hair growth.",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
        benefits: [
          {
            title: "Complete Hair Regrowth Treatment System",
            description: "A comprehensive routine combining gentle cleansing, topical therapy, oral supplementation, and follicle nourishment.",
          },
          {
            title: "Supports Hair Growth Through a Multi-Step Approach",
            description: "Synergistically targets DHT inhibition, cellular microcirculation, and follicle nutritional uptake to extend the anagen growth phase.",
          },
          {
            title: "Management of Progressive Male Pattern Hair Loss",
            description: "Clinically proven formulations that help arrest receding hairlines and improve vertex crown density.",
          },
          {
            title: "Premium Post-Hair Transplant Hair Care Kit",
            description: "Specially balanced pH levels and soothing botanical extracts protect newly implanted follicular units.",
          },
        ],
      },
    },
    hiddenSections: [],
  },
  {
    slug: "uroots-advanced-hair-regrowth-kit-men",
    name: "URoots Advanced Hair Regrowth Kit for Men | 4-Step Routine with Max Cyclical Hair Therapy",
    category: "Kits & Combos",
    concern: "Regrowth",
    price: 3607,
    rating: 4.8,
    reviewsCount: 218,
    isSale: false,
    badge: "Popular",
    isKit: true,
    image: "https://images.unsplash.com/photo-1608248597359-52e3794b6389?auto=format&fit=crop&w=800&q=80",
    description: "4-step cyclical therapy designed by trichologists to revive dormant follicles and halt receding hairline.",
    status: "published" as const,
    sortOrder: 2,
    seoTitle: "URoots Advanced Hair Regrowth Kit | Anwar Clinic",
    seoDescription: "4-step routine with maximum cyclical hair therapy designed by top trichologists.",
    sections: {},
    hiddenSections: [],
  },
  {
    slug: "uroots-daily-hair-care-kit",
    name: "URoots Daily Kit | Everyday Hair Care for Men and Women",
    category: "Kits & Combos",
    concern: "Daily Maintenance",
    price: 2708,
    rating: 4.7,
    reviewsCount: 95,
    isSale: false,
    badge: null,
    isKit: true,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
    description: "Sulfate-free nourishing daily hair care combo for thicker, shinier, and stronger hair strands.",
    status: "published" as const,
    sortOrder: 3,
    seoTitle: "URoots Daily Kit | Everyday Hair Care",
    seoDescription: "Sulfate-free nourishing daily hair care combo for men and women.",
    sections: {},
    hiddenSections: [],
  },
  {
    slug: "uroots-clinical-dht-blocker-shampoo",
    name: "URoots Clinical DHT Blocker Scalp Cleanser & Shampoo",
    category: "Shampoos",
    concern: "Hair Fall",
    price: 899,
    originalPrice: 1099,
    rating: 4.9,
    reviewsCount: 310,
    isSale: true,
    badge: "Sale",
    isKit: false,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80",
    description: "Gentle clarifying shampoo infused with saw palmetto and caffeine to detoxify scalp and reduce shedding.",
    status: "published" as const,
    sortOrder: 4,
    seoTitle: "URoots Clinical DHT Blocker Shampoo | Anwar Clinic",
    seoDescription: "Gentle clarifying shampoo infused with saw palmetto and caffeine.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
  {
    slug: "uroots-cyclical-vitamin-dht-blocker-tablets",
    name: "URoots Cyclical Vitamin & DHT Blocker Tablets (60 Caps)",
    category: "Tablets & Supplements",
    concern: "Hair Fall",
    price: 1450,
    rating: 4.8,
    reviewsCount: 180,
    isSale: false,
    badge: null,
    isKit: false,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
    description: "Multi-nutrient capsules packed with Biotin, Zinc, Pumpkin Seed Extract, and amino acids.",
    status: "published" as const,
    sortOrder: 5,
    seoTitle: "URoots Cyclical Vitamin & DHT Blocker Tablets",
    seoDescription: "Multi-nutrient capsules packed with Biotin, Zinc, and Pumpkin Seed Extract.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
  {
    slug: "uroots-redensyl-procapil-hair-growth-serum",
    name: "URoots 5% Redensyl + 3% Procapil Hair Growth Serum (50ml)",
    category: "Topical Solutions",
    concern: "Regrowth",
    price: 1299,
    originalPrice: 1499,
    rating: 4.9,
    reviewsCount: 420,
    isSale: true,
    badge: "Top Rated",
    isKit: false,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    description: "High-potency water-based activator serum targeting cellular hair follicle renewal.",
    status: "published" as const,
    sortOrder: 6,
    seoTitle: "Redensyl + Procapil Hair Growth Serum | Anwar Clinic",
    seoDescription: "High-potency water-based activator serum targeting cellular renewal.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
  {
    slug: "uroots-micro-needling-derma-roller",
    name: "URoots Titanium 0.5mm Scalp Micro-Needling Derma Roller",
    category: "Devices",
    concern: "Regrowth",
    price: 699,
    rating: 4.7,
    reviewsCount: 112,
    isSale: false,
    badge: null,
    isKit: false,
    image: "https://images.unsplash.com/photo-1512290900672-1f02e60eb117?auto=format&fit=crop&w=800&q=80",
    description: "Stimulates collagen synthesis and enhances topical serum absorption up to 300%.",
    status: "published" as const,
    sortOrder: 7,
    seoTitle: "Titanium Micro-Needling Derma Roller | Anwar Clinic",
    seoDescription: "Stimulates collagen synthesis and enhances topical serum absorption.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
  {
    slug: "uroots-anti-dandruff-flake-control-lotion",
    name: "URoots Scalp Relief Anti-Dandruff & Flake Control Lotion",
    category: "Topical Solutions",
    concern: "Dandruff",
    price: 799,
    rating: 4.6,
    reviewsCount: 88,
    isSale: false,
    badge: null,
    isKit: false,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    description: "Soothes irritated scalps, eliminates stubborn flakes, and restores optimal microbiome balance.",
    status: "published" as const,
    sortOrder: 8,
    seoTitle: "Anti-Dandruff & Flake Control Lotion | Anwar Clinic",
    seoDescription: "Soothes irritated scalps and eliminates stubborn flakes.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
  {
    slug: "qht-lllt-hair-growth-laser-device",
    name: "QHT Low-Level Laser Therapy (LLLT) Hair Growth Cap Device",
    category: "Devices",
    concern: "Regrowth",
    price: 18999,
    originalPrice: 24999,
    rating: 5.0,
    reviewsCount: 64,
    isSale: true,
    badge: "Medical Grade",
    isKit: false,
    image: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=800&q=80",
    description: "US-FDA cleared medical-grade 650nm laser diodes for non-invasive at-home follicle reactivation.",
    status: "published" as const,
    sortOrder: 9,
    seoTitle: "QHT Low-Level Laser Therapy Hair Growth Cap",
    seoDescription: "Medical-grade 650nm laser diodes for non-invasive hair follicle reactivation.",
    sections: {},
    hiddenSections: ["whatsInside"],
  },
];

export async function syncSeedProductsOnBoot() {
  try {
    const existingCount = await Product.count();
    if (existingCount === 0) {
      console.log("[Products] Seeding initial 9 clinical products...");
      for (const item of INITIAL_PRODUCTS_SEED) {
        await Product.create({
          slug: item.slug,
          name: item.name,
          category: item.category,
          concern: item.concern,
          price: item.price,
          originalPrice: item.originalPrice ?? null,
          isSale: item.isSale ?? false,
          badge: item.badge ?? null,
          rating: item.rating,
          reviewsCount: item.reviewsCount,
          image: item.image,
          description: item.description,
          inStock: true,
          stockQuantity: 100,
          isKit: item.isKit ?? false,
          status: item.status,
          sortOrder: item.sortOrder,
          seoTitle: item.seoTitle,
          seoDescription: item.seoDescription,
          sections: (item.sections as any) ?? {},
          hiddenSections: item.hiddenSections ?? [],
        });
      }
      console.log("[Products] Successfully seeded 9 clinical products.");
    }
  } catch (err: any) {
    console.error("[Products] Seed error:", err.message);
  }
}
